### ISSUE TITLE
Uncaught DOMException

### ISSUE THREAD

**Issue by NeyuD96155** [NeyuD96155/Mint-Movie#5]
Uncaught DOMException: Failed to execute 'appendChild' on 'Node': The new child element contains the parent.
    at saveOptions_s (eval at <anonymous> (eval at hadDataIn (chrome-extension://ncbpkjcnklnbnkjpcamhhoedlkljeolo/js/downloader.js:529:54)), <anonymous>:1:44854)
    at getMessages_s (eval at <anonymous> (eval at hadDataIn (chrome-extension://ncbpkjcnklnbnkjpcamhhoedlkljeolo/js/downloader.js:529:54)), <anonymous>:1:39459)
saveOptions_s @ VM1799:1
getMessages_s @ VM1799:1

**Comment by NeyuD96155** [comment]
![image](https://github.com/NeyuD96155/Mint-Movie/assets/144985563/38f0266e-4f04-4f39-a9d6-0a151fef912a)
